services:

  zlagoda-db:
    image: postgres:17.6
    container_name: postgres-db
    environment:
      POSTGRES_DB: zlagoda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - zlagoda-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d zlagoda" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate-db:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database",  "postgresql://postgres:postgres@zlagoda-db:5432/zlagoda?sslmode=disable", "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - zlagoda-db
    restart: "no"

  go-server:
    build:
      context: .
      dockerfile: go-server/deployment/Dockerfile
      target: dev
    depends_on:
      zlagoda-db:
        condition: service_healthy
    env_file:
      - go-server/.env.example
    volumes:
      - ./go-server:/app/go-server
    ports:
      - "8080:8080"
    restart: on-failure

  java-server:
    build:
      context: ./java-server
      dockerfile: Dockerfile.dev
    depends_on:
      zlagoda-db:
        condition: service_healthy
    env_file:
      - java-server/.env.example
    volumes:
      - ./java-server:/app
    ports:
      - "8081:8080"
      - "5005:5005"
    restart: unless-stopped

volumes:
  zlagoda-db-data:
