services:

  zlagoda-db:
    image: postgres:17.6
    container_name: postgres-db
    environment:
      POSTGRES_DB: zlagoda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - zlagoda-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d zlagoda" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  go-server:
    build:
      context: .
      dockerfile: go-server/deployment/Dockerfile
      target: dev
    depends_on:
      zlagoda-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@zlagoda:5432/zlagoda?sslmode=disable
    volumes:
      - ./go-server:/app/go-server
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  zlagoda-db-data:
